---
# tasks file to start adminer container

- name: "{{ 'Create' if (state is undefined or 'absent' not in state) else 'Terminate' }} adminer container"
  docker_container:
    name: adminer
    image: adminer:{{ docker_adminer_image }}
    restart_policy: always
    tty: yes
    ports:
      - "8080:8080"
    links: 
      - 'nextcloud-db:db'
    networks:
      - name: backend
    networks_cli_compatible: true
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    state: "{{ state | default('started') }}"
      